#!/bin/bash

if [ ! -f ../usr/bin/activate ]
then
	conda create -p ../usr "python>3"
fi

source activate ../usr

conda install numpy scipy pip
conda install -c aseyboldt tpp openms
pip install git+https://github.com/hroest/msproteomicstools.git@feature/python3
